=== tlplatz/Enigma-Cipher-Machine/EnigmaCipherMachine/E/Docs/Settings.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xsd:element name="MonthlySettings">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Year" type="xsd:unsignedShort" />
        <xsd:element name="Month" type="xsd:unsignedByte" />
        <xsd:element name="DailySettings">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element minOccurs="28" maxOccurs="31" name="Settings">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Day" type="xsd:unsignedByte" />
                    <xsd:element name="MachineType" type="xsd:string" />
                    <xsd:element name="ReflectorType" type="xsd:string" />
                    <xsd:element name="Rotors">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element minOccurs="3" maxOccurs="4" name="RotorSetting">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="Name" type="xsd:string" />
                                <xsd:element name="RingSetting" type="xsd:unsignedByte" />
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="Plugs">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element minOccurs="10" maxOccurs="10" name="PlugSetting">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="LetterA" type="xsd:string" />
                                <xsd:element name="LetterB" type="xsd:string" />
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xs:schema>

=== tlplatz/Enigma-Cipher-Machine/EnigmaCipherMachine/E/Docs/M4K/January_2016/January_2016_Settings.xml
<?xml version="1.0"?>
<MonthlySettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Year="2016" Month="1" Title="Settings" xsi:noNamespaceSchemaLocation="Settings.xsd">
  <DailySettings>
    <Settings Day="31" MachineType="M4K" ReflectorType="B_Dunn" Grund="MKOX" Kenngruppen="">
      <Rotors>
        <RotorSetting Name="Beta" RingSetting="10" />
        <RotorSetting Name="IV" RingSetting="16" />
        <RotorSetting Name="VII" RingSetting="6" />
        <RotorSetting Name="III" RingSetting="17" />
      </Rotors>
      <Plugs>
        <PlugSetting LetterA="C" LetterB="K" />
        <PlugSetting LetterA="D" LetterB="J" />
        <PlugSetting LetterA="E" LetterB="I" />
        <PlugSetting LetterA="F" LetterB="H" />
        <PlugSetting LetterA="L" LetterB="S" />
        <PlugSetting LetterA="M" LetterB="Z" />
        <PlugSetting LetterA="O" LetterB="X" />
        <PlugSetting LetterA="P" LetterB="Q" />
        <PlugSetting LetterA="T" LetterB="Y" />
        <PlugSetting LetterA="U" LetterB="W" />
      </Plugs>
    </Settings>
    <Settings Day="30" MachineType="M4K" ReflectorType="B_Dunn" Grund="WULN" Kenngruppen="">
      <Rotors>
        <RotorSetting Name="Beta" RingSetting="19" />
        <RotorSetting Name="V" RingSetting="16" />
        <RotorSetting Name="VII" RingSetting="0" />
        <RotorSetting Name="III" RingSetting="23" />
      </Rotors>
      <Plugs>
        <PlugSetting LetterA="A" LetterB="Z" />
        <PlugSetting LetterA="C" LetterB="I" />
        <PlugSetting LetterA="D" LetterB="K" />
        <PlugSetting LetterA="E" LetterB="S" />
        <PlugSetting LetterA="G" LetterB="X" />
        <PlugSetting LetterA="J" LetterB="N" />
        <PlugSetting LetterA="L" LetterB="V" />
        <PlugSetting LetterA="O" LetterB="U" />
        <PlugSetting LetterA="R" LetterB="T" />
        <PlugSetting LetterA="W" LetterB="Y" />
      </Plugs>
    </Settings>
    <Settings Day="29" MachineType="M4K" ReflectorType="C_Dunn" Grund="QFHN" Kenngruppen="">
      <Rotors>
        <RotorSetting Name="Beta" RingSetting="8" />
        <RotorSetting Name="I" RingSetting="4" />
        <RotorSetting Name="II" RingSetting="11" />
        <RotorSetting Name="V" RingSetting="17" />
      </Rotors>
      <Plugs>
        <PlugSetting LetterA="A" LetterB="X" />
        <PlugSetting LetterA="B" LetterB="P" />
        <PlugSetting LetterA="D" LetterB="I" />
        <PlugSetting LetterA="F" LetterB="K" />
        <PlugSetting LetterA="H" LetterB="O" />
        <PlugSetting LetterA="L" LetterB="Z" />
        <PlugSetting LetterA="M" LetterB="N" />
        <PlugSetting LetterA="Q" LetterB="S" />
        <PlugSetting LetterA="T" LetterB="V" />
        <PlugSetting LetterA="W" LetterB="Y" />
      </Plugs>
    </Settings>
    <Settings Day="28" MachineType="M4K" ReflectorType="C_Dunn" Grund="DJIH" Kenngruppen="">
      <Rotors>
        <RotorSetting Name="Gamma" RingSetting="21" />
        <RotorSetting Name="VI" RingSetting="6" />
        <RotorSetting Name="VIII" RingSetting="0" />
        <RotorSetting Name="IV" RingSetting="24" />
      </Rotors>
      <Plugs>
        <PlugSetting LetterA="B" LetterB="M" />
        <PlugSetting LetterA="C" LetterB="P" />
        <PlugSetting LetterA="D" LetterB="N" />
        <PlugSetting LetterA="E" LetterB="I" />
        <PlugSetting LetterA="F" LetterB="R" />
        <PlugSetting LetterA="G" LetterB="Z" />
        <PlugSetting LetterA="H" LetterB="U" />
        <PlugSetting LetterA="J" LetterB="V" />
        <PlugSetting LetterA="L" LetterB="O" />
        <PlugSetting LetterA="T" LetterB="X" />
      </Plugs>
    </Settings>
    <Settings Day="27" MachineType="M4K" ReflectorType="C_Dunn" Grund="JWCE" Kenngruppen="">
      <Rotors>
        <RotorSetting Name="Gamma" RingSetting="7" />
        <RotorSetting Name="III" RingSetting="23" />
        <RotorSetting Name="I" RingSetting="20" />
        <RotorSetting Name="VII" RingSetting="15" />
      </Rotors>
      <Plugs>
        <PlugSetting LetterA="A" LetterB="L" />
        <PlugSetting LetterA="B" LetterB="N" />
        <PlugSetting LetterA="E" LetterB="K" />
        <PlugSetting LetterA="F" LetterB="Y" />
        <PlugSetting LetterA="G" LetterB="W" />
        <PlugSetting LetterA="H" LetterB="P" />
        <PlugSetting LetterA="I" LetterB="X" />
        <PlugSetting LetterA="J" LetterB="Z" />
        <PlugSetting LetterA="M" LetterB="T" />
        <PlugSetting LetterA="O" LetterB="Q" />
      </Plugs>
    </Settings>
    <Settings Day="26" MachineType="M4K" ReflectorType="C_Dunn" Grund="ESAS" Kenngruppen="">
      <Rotors>
        <RotorSetting Name="Beta" RingSetting="11" />
        <RotorSetting Name="II" RingSetting="16" />
        <RotorSetting Name="V" RingSetting="8" />
        <RotorSetting Name="VI" RingSetting="18" />
      </Rotors>
      <Plugs>
        <PlugSetting LetterA="A" LetterB="C" />
        <PlugSetting LetterA="B" LetterB="X" />
        <PlugSetting LetterA="D" LetterB="J" />
        <PlugSetting LetterA="E" LetterB="T" />
        <PlugSetting LetterA="F" LetterB="R" />
        <PlugSetting LetterA="G" LetterB="W" />
        <PlugSetting LetterA="H" LetterB="N" />
        <PlugSetting LetterA="I" LetterB="Z" />
        <PlugSetting LetterA="K" LetterB="P" />
        <PlugSetting LetterA="M" LetterB="V" />
      </Plugs>
    </Settings>
    <Settings Day="25" MachineType="M4K" ReflectorType="C_Dunn" Grund="BMCT" Kenngruppen="">
      <Rotors>
        <RotorSetting Name="Beta" RingSetting="14" />
        <RotorSetting Name="VI" RingSetting="6" />
        <RotorSetting Name="IV" RingSetting="9" />
        <RotorSetting Name="II" RingSetting="1" />
      </Rotors>
      <Plugs>
        <PlugSetting LetterA="A" LetterB="Z" />
        <PlugSetting LetterA="B" LetterB="P" />
        <PlugSetting LetterA="C" LetterB="W" />
        <PlugSetting LetterA="D" LetterB="O" />
        <PlugSetting LetterA="E" LetterB="U" />
        <PlugSetting LetterA="F" LetterB="K" />
        <PlugSetting LetterA="G" LetterB="Q" />
        <PlugSetting LetterA="H" LetterB="Y" />
        <PlugSetting LetterA="N" LetterB="T" />
        <PlugSetting LetterA="R" LetterB="V" />
      </Plugs>
    </Settings>
    <Settings Day="24" MachineType="M4K" ReflectorType="C_Dunn" Grund="MZCA" Kenngruppen="">
      <Rotors>
        <RotorSetting Name="Gamma" RingSetting="0" />
        <RotorSetting Name="V" RingSetting="25" />
        <RotorSetting Name="II" RingSetting="23" />
        <RotorSetting Name="IV" RingSetting="11" />
      </Rotors>
      <Plugs>
        <PlugSetting LetterA="A" LetterB="B" />
        <PlugSetting LetterA="D" LetterB="M" />
        <PlugSetting LetterA="E" LetterB="P" />
        <PlugSetting LetterA="F" LetterB="N" />
        <PlugSetting LetterA="H" LetterB="J" />
        <PlugSetting LetterA="I" LetterB="S" />
        <PlugSetting LetterA="K" LetterB="L" />
        <PlugSetting LetterA="Q" LetterB="Y" />
        <PlugSetting LetterA="T" LetterB="Z" />
        <PlugSetting LetterA="V" LetterB="X" />
      </Plugs>
    </Settings>
    <Settings Day="23" MachineType="M4K" ReflectorType="C_Dunn" Grund="FFRE" Kenngruppen="">
      <Rotors>
        <RotorSetting Name="Gamma" RingSetting="25" />
        <RotorSetting Name="V" RingSetting="23" />
        <RotorSetting Name="VI" RingSetting="2" />
        <RotorSetting Name="III" RingSetting="18" />
      </Rotors>
      <Plugs>
        <PlugSetting LetterA="A" LetterB="N" />
        <PlugSetting LetterA="B" LetterB="P" />
        <PlugSetting LetterA="C" LetterB="O" />
        <PlugSetting LetterA="E" LetterB="H" />
        <PlugSetting LetterA="G" LetterB="Y" />
        <PlugSetting LetterA="I" LetterB="U" />
        <PlugSetting LetterA="J" LetterB="X" />
        <PlugSetting LetterA="L" LetterB="T" />
        <PlugSetting LetterA="M" LetterB="V" />
        <PlugSetting LetterA="R" LetterB="S" />
      </Plugs>
    </Settings>
    <Settings Day="22" MachineType="M4K" ReflectorType="B_Dunn" Grund="XRJS" Kenngruppen="">
      <Rotors>
        <RotorSetting Name="Beta" RingSetting="7" />
        <RotorSetting Name="V" RingSetting="3" />
        <RotorSetting Name="III" RingSetting="8" />
        <RotorSetting Name="IV" RingSetting="2" />
      </Rotors>
      <Plugs>
        <PlugSetting LetterA="A" LetterB="J" />
        <PlugSetting LetterA="B" LetterB="V" />
        <PlugSetting LetterA="D" LetterB="S" />
        <PlugSetting LetterA="E" LetterB="M" />
        <PlugSetting LetterA="F" LetterB="T" />
        <PlugSetting LetterA="G" LetterB="R" />
        <PlugSetting LetterA="I" LetterB="Q" />
        <PlugSetting LetterA="K" LetterB="X" />
        <PlugSetting LetterA="U" LetterB="Z" />
        <PlugSetting LetterA="W" LetterB="Y" />
      </Plugs>
    </Settings>
    <Settings Day="21" MachineType="M4K" ReflectorType="C_Dunn" Grund="BLMS" Kenngruppen="">
      <Rotors>
        <RotorSetting Name="Beta" RingSetting="17" />
        <RotorSetting Name="VII" RingSetting="3" />
        <RotorSetting Name="VI" RingSetting="19" />
        <RotorSetting Name="II" RingSetting="12" />
      </Rotors>
      <Plugs>
        <PlugSetting LetterA="A" LetterB="T" />
        <PlugSetting LetterA="B" LetterB="E" />
        <PlugSetting LetterA="D" LetterB="X" />
        <PlugSetting LetterA="F" LetterB="P" />
        <PlugSetting LetterA="I" LetterB="Y" />
        <PlugSetting LetterA="J" LetterB="V" />
        <PlugSetting LetterA="K" LetterB="L" />
        <PlugSetting LetterA="N" LetterB="O" />
        <PlugSetting LetterA="R" LetterB="Z" />
        <PlugSetting LetterA="U" LetterB="W" />
      </Plugs>
    </Settings>
    <Settings Day="20" MachineType="M4K" ReflectorType="B_Dunn" Grund="WOSD" Kenngruppen="">
